# -*- coding: utf-8 -*-
import os
import struct
import numpy as np
import io

# ====== SET YOUR FILE PATH HERE ======
DAT_FILE_PATH = "/Users/zahed_riyaz/Documents/prbh/BlackHolesDarkDress/Nbody/run/PBH1.dat"
# =====================================


def read_gadget_header(f):
    # read block size and then the 256-byte header
    block_bytes = f.read(4)
    if not block_bytes:
        raise EOFError("Unexpected EOF while reading header block size")
    nbytes = struct.unpack('<I', block_bytes)[0]
    hdr = f.read(nbytes)
    f.read(4)            # closing block size

    buf = io.BytesIO(hdr)
    hdr_struct = {}

    hdr_struct['NumPart_ThisFile'] = np.frombuffer(buf.read(24), '<u4')
    hdr_struct['MassTable'] = np.frombuffer(buf.read(48), '<f8')
    hdr_struct['Time'], hdr_struct['Redshift'] = struct.unpack('<dd', buf.read(16))
    hdr_struct['Flag_Sfr'], hdr_struct['Flag_Feedback'] = struct.unpack('<ii', buf.read(8))
    hdr_struct['NumPart_Total'] = np.frombuffer(buf.read(24), '<u4')
    hdr_struct['Flag_Cooling'], hdr_struct['NumFilesPerSnapshot'] = struct.unpack('<ii', buf.read(8))
    hdr_struct['BoxSize'], hdr_struct['Omega0'], hdr_struct['OmegaLambda'], hdr_struct['HubbleParam'] = struct.unpack('<dddd', buf.read(32))
    hdr_struct['Flag_StellarAge'], hdr_struct['Flag_Metals'] = struct.unpack('<ii', buf.read(8))
    # remaining bytes are padding

    return hdr_struct


def read_block(f, count, dtype):
    nbytes = struct.unpack('<I', f.read(4))[0]
    data = np.fromfile(f, dtype=dtype, count=count)
    f.read(4)
    return data


def read_gadget_body(f, header):
    nptot = int(np.sum(header['NumPart_ThisFile']))
    pos = read_block(f, 3*nptot, '<f4').reshape((nptot,3))
    vel = read_block(f, 3*nptot, '<f4').reshape((nptot,3))
    ids = read_block(f, nptot, '<u4')
    mass = read_block(f, nptot, '<f4')
    ngas = int(header['NumPart_ThisFile'][0])
    u = read_block(f, ngas, '<f4')
    return pos, vel, ids, mass, u


def read_dat_file(file_path):
    """Read a Gadget‑2 binary IC file and return header+arrays.

    Parameters
    ----------
    file_path : str
        Path to the .dat file generated by pygadgetic / Gadget.

    Returns
    -------
    tuple
        (header_dict, pos, vel, ids, mass, u)
    """
    if not os.path.exists(file_path):
        raise IOError("File does not exist: %s" % file_path)

    with open(file_path, "rb") as f:
        hdr = read_gadget_header(f)
        print("Header contents:")
        for k, v in hdr.items():
            print("  %-20s %s" % (k, str(v)))
        print()

        pos, vel, ids, mass, u = read_gadget_body(f, hdr)
        print("read %d particles" % pos.shape[0])
        print("first 5 positions:", pos[:5])
        print("first 5 velocities:", vel[:5])
        print("first 5 ids:", ids[:5])
        print("first 5 masses:", mass[:5])
        print("u array length:", u.shape)

        return hdr, pos, vel, ids, mass, u


# ---------------------------------------------------------------------------
# animation helpers
# ---------------------------------------------------------------------------

import matplotlib
# use non‑interactive backend so script runs on macOS CLI
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from mpl_toolkits.mplot3d import Axes3D


def animate_rotation(pos, savepath=None, elev=30, frames=60, interval=100, max_points=10000):
    """Create a rotation animation of 3D positions.

    The function will subsample the point cloud if it is very large to
    keep rendering times reasonable.

    Parameters
    ----------
    pos : ndarray, shape (N,3)
        Particle coordinates.
    savepath : str or None
        If provided, the animation is written to this file (e.g. .mp4).
    elev : float
        Elevation angle for the camera.
    frames : int or sequence
        Number of azimuth steps or iterable of angles.
    interval : int
        Delay between frames in ms.
    max_points : int
        Maximum number of points to plot (randomly sampled if exceeded).

    Returns
    -------
    FuncAnimation
        The animation object.
    """
    n = pos.shape[0]
    if n > max_points:
        idx = np.random.choice(n, max_points, replace=False)
        pos = pos[idx]
        print("downsampled to %d points for animation" % max_points)

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    scat = ax.scatter(pos[:,0], pos[:,1], pos[:,2], s=1, lw=0)
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('z')
    # older matplotlib versions don't have set_box_aspect

    if np.isscalar(frames):
        angles = np.linspace(0, 360, frames)
    else:
        angles = frames

    def update(angle):
        ax.view_init(elev=elev, azim=angle)
        return scat,

    ani = FuncAnimation(fig, update, frames=angles, interval=interval, blit=True)
    if savepath:
        print("saving animation to %s (%d frames)" % (savepath, len(angles)))
        ani.save(savepath, writer='ffmpeg')
    else:
        plt.show()
    return ani


if __name__ == "__main__":
    hdr, pos, vel, ids, mass, u = read_dat_file(DAT_FILE_PATH)
    # generate a simple rotation animation in the XY plane
    outname = os.path.splitext(os.path.basename(DAT_FILE_PATH))[0] + "_rot.mp4"
    outpath = os.path.join(os.path.dirname(DAT_FILE_PATH), outname)
    print("creating animation", outpath)
    animate_rotation(pos, savepath=outpath)
